### ISSUE TITLE
Match property format for Spring3

### ISSUE THREAD

**Issue by CodyPolton** [micrometer-metrics/prometheus-rsocket-proxy#78] opened 2024-03-20 15:14 UTC
Going off this [documentation](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#actuator-metrics-export-properties) to migrate to spring3 the properties for exporting metrics changed from management.metrics.export.prometheus to  management.prometheus.metrics.export. This doesn't appear to be reflected for rsocket settings which tripped me up. I had migrate management.metrics.export.prometheus.rsocket.host to management.prometheus.metrics.export.rsocket.host which broke my implementation. Didn't realize that those properties we unrelated to each other.

**Comment by jonatan-ivanov** [comment] 2024-03-20 17:47
We have a PR for this, please let us know your preference here: https://github.com/micrometer-metrics/prometheus-rsocket-proxy/pull/77

**Comment by jonatan-ivanov** [comment] 2024-03-20 17:47
Duplicate of https://github.com/micrometer-metrics/prometheus-rsocket-proxy/pull/77

**Closed by jonatan-ivanov** 2024-03-20 17:47 UTC
